# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: iso_countries_plus 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "iso_countries_plus"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mark Dickson"]
  s.date = "2015-10-01"
  s.description = "This gem differs from other ISO country gems in that it allows VERY flexible name lookups, so country names like 'South Korea' will work properly."
  s.email = "mark@sitesteaders.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/iso_countries_plus.rb",
    "lib/iso_countries_plus/additions.yml",
    "lib/iso_countries_plus/assign.rb",
    "lib/iso_countries_plus/country.rb",
    "lib/iso_countries_plus/country_continents.csv",
    "lib/iso_countries_plus/countrynames.txt",
    "lib/iso_countries_plus/init.rb",
    "lib/iso_countries_plus/iso_country.rb",
    "test/helper.rb",
    "test/test_iso_countries_plus.rb"
  ]
  s.homepage = "http://github.com/ideaoforder/iso_countries_plus"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "ISO Countries, including all standard name variations, alpha2, and alpha3"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

